import { VerifiedResource } from "@/types";

export const VERIFIED_INDIA_RESOURCES: VerifiedResource[] = [
  // ------------------------------------------------------------
  // NATIONAL OFFICIAL STATUTORY SERVICES (TIER 1)
  // ------------------------------------------------------------
  {
    id: "res-nat-112",
    name: "National Emergency Response Support System (ERSS - 112)",
    organizationName: "Ministry of Home Affairs (MHA), Govt of India",
    serviceType: "EMERGENCY_POLICE",
    description: "Pan-India single emergency number for immediate police, fire, and ambulance dispatch in life-threatening situations.",
    address: "National Unified Command Center",
    state: "National",
    district: "All Districts",
    contact: "112",
    secondaryContact: null,
    website: "https://112.gov.in",
    operatingHours: "24/7",
    is24x7: true,
    eligibility: "Available to any person in India in distress",
    availability: "AVAILABLE",
    geographicScope: "NATIONAL",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_1_OFFICIAL_GOVERNMENT",
    lastVerified: "2026-08-15T00:00:00Z",
    nextReview: "2026-11-15T00:00:00Z",
    sourceOrganization: "Ministry of Home Affairs Gazette",
    sourceUrl: "https://112.gov.in",
    services: [
      { category: "EMERGENCY", name: "Immediate Emergency Dispatch", isFree: true },
      { category: "LEGAL", name: "Police First Response", isFree: true },
    ],
    isDemo: false,
  },
  {
    id: "res-nat-1091",
    name: "National Women Helpline (1091)",
    organizationName: "Ministry of Women and Child Development (MWCD)",
    serviceType: "HELPLINE",
    description: "24/7 dedicated toll-free helpline providing immediate response, crisis intervention, police liaison, and shelter referral for women facing violence or harassment.",
    address: "National Network",
    state: "National",
    district: "All Districts",
    contact: "1091",
    secondaryContact: "181",
    website: "https://wcd.nic.in",
    operatingHours: "24/7",
    is24x7: true,
    eligibility: "Any woman or ally seeking guidance or crisis intervention",
    availability: "AVAILABLE",
    geographicScope: "NATIONAL",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_1_OFFICIAL_GOVERNMENT",
    lastVerified: "2026-08-20T00:00:00Z",
    nextReview: "2026-11-20T00:00:00Z",
    sourceOrganization: "MWCD Official Portal",
    sourceUrl: "https://wcd.nic.in",
    services: [
      { category: "EMOTIONAL", name: "Crisis De-escalation", isFree: true },
      { category: "LEGAL", name: "Police & Shelter Referral", isFree: true },
      { category: "EMERGENCY", name: "Emergency Women Police Dispatch", isFree: true },
    ],
    isDemo: false,
  },
  {
    id: "res-nat-telemanas",
    name: "Tele-MANAS (National Tele Mental Health Programme)",
    organizationName: "Ministry of Health and Family Welfare (MoHFW) / NIMHANS",
    serviceType: "HELPLINE",
    description: "Comprehensive 24/7 free mental health counseling helpline delivering psychological first aid, trauma stabilization, and referral to district mental health units in 20+ languages.",
    address: "National Hub at NIMHANS, Bengaluru",
    state: "National",
    district: "All Districts",
    contact: "14416",
    secondaryContact: "1800-891-4416",
    website: "https://telemanas.mohfw.gov.in",
    operatingHours: "24/7",
    is24x7: true,
    eligibility: "Open to anyone experiencing distress, panic, anxiety, or trauma",
    availability: "AVAILABLE",
    geographicScope: "NATIONAL",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_1_OFFICIAL_GOVERNMENT",
    lastVerified: "2026-08-10T00:00:00Z",
    nextReview: "2026-11-10T00:00:00Z",
    sourceOrganization: "Ministry of Health and Family Welfare",
    sourceUrl: "https://telemanas.mohfw.gov.in",
    services: [
      { category: "EMOTIONAL", name: "Trauma Psychological First Aid", isFree: true },
      { category: "EMOTIONAL", name: "Multilingual Psychiatric Counseling", isFree: true },
    ],
    isDemo: false,
  },
  {
    id: "res-nat-nalsa",
    name: "National Legal Services Authority (NALSA) Legal Aid Helpline",
    organizationName: "National Legal Services Authority (Supreme Court of India)",
    serviceType: "LEGAL_AID",
    description: "Toll-free national helpline connecting women, children, and custody victims to free legal counsel under Section 12 of the Legal Services Authorities Act.",
    address: "B-Block, Additional Office Complex, Supreme Court of India, New Delhi",
    state: "National",
    district: "All Districts",
    contact: "15100",
    secondaryContact: null,
    website: "https://nalsa.gov.in",
    operatingHours: "9:30 AM - 6:00 PM (Monday-Saturday)",
    is24x7: false,
    eligibility: "All women, children, and persons eligible under Section 12 LSA Act",
    availability: "AVAILABLE",
    geographicScope: "NATIONAL",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_1_OFFICIAL_GOVERNMENT",
    lastVerified: "2026-08-01T00:00:00Z",
    nextReview: "2026-11-01T00:00:00Z",
    sourceOrganization: "NALSA Official Portal",
    sourceUrl: "https://nalsa.gov.in",
    services: [
      { category: "LEGAL", name: "Free Legal Aid & Advocate Assignment", isFree: true },
      { category: "LEGAL", name: "BNS / FIR Procedure Guidance", isFree: true },
    ],
    isDemo: false,
  },
  {
    id: "res-nat-childline",
    name: "Childline India (1098 / Emergency POCSO Support)",
    organizationName: "Ministry of Women & Child Development (MWCD)",
    serviceType: "HELPLINE",
    description: "Dedicated 24-hour emergency phone outreach service for children in need of care and protection, mandatorily responding to cases under the POCSO Act.",
    address: "MWCD Emergency Response Grid",
    state: "National",
    district: "All Districts",
    contact: "1098",
    secondaryContact: "112",
    website: "https://wcd.nic.in",
    operatingHours: "24/7",
    is24x7: true,
    eligibility: "Minors under 18 years, parents, guardians, and concerned citizens",
    availability: "AVAILABLE",
    geographicScope: "NATIONAL",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_1_OFFICIAL_GOVERNMENT",
    lastVerified: "2026-08-12T00:00:00Z",
    nextReview: "2026-11-12T00:00:00Z",
    sourceOrganization: "MWCD Notification",
    sourceUrl: "https://wcd.nic.in",
    services: [
      { category: "EMERGENCY", name: "Child Emergency Rescue", isFree: true },
      { category: "LEGAL", name: "POCSO Reporting & Child Welfare Committee Support", isFree: true },
    ],
    isDemo: false,
  },

  // ------------------------------------------------------------
  // STATE & DISTRICT LEVEL RESOURCES (DELHI NCT)
  // ------------------------------------------------------------
  {
    id: "res-dl-osc-aiims",
    name: "One Stop Centre (Sakhi) — AIIMS New Delhi",
    organizationName: "Govt of NCT of Delhi / AIIMS",
    serviceType: "ONE_STOP_CENTRE",
    description: "Integrated facility providing emergency medical care (PEP, contraception, wound treatment), forensic sample preservation, psycho-social counseling, police facilitation, and legal aid under one roof.",
    address: "All India Institute of Medical Sciences (AIIMS), Ansari Nagar",
    state: "Delhi",
    district: "South Delhi",
    contact: "+91-11-26588500",
    secondaryContact: "181",
    website: "https://www.aiims.edu",
    operatingHours: "24/7 Emergency Care",
    is24x7: true,
    eligibility: "Any woman or child affected by violence",
    availability: "AVAILABLE",
    geographicScope: "DISTRICT",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_1_OFFICIAL_GOVERNMENT",
    lastVerified: "2026-08-25T00:00:00Z",
    nextReview: "2026-11-25T00:00:00Z",
    sourceOrganization: "Ministry of Women & Child Development Directory",
    sourceUrl: "https://wcd.nic.in/schemes/one-stop-centre-scheme-1",
    services: [
      { category: "MEDICAL", name: "HIV Post-Exposure Prophylaxis (PEP) & Forensic Exam", isFree: true },
      { category: "EMOTIONAL", name: "On-site Crisis Counseling", isFree: true },
      { category: "LEGAL", name: "DLSA Free Legal Representation & FIR Desk", isFree: true },
      { category: "SHELTER", name: "Temporary Short-Stay Shelter (Up to 5 Days)", isFree: true },
    ],
    isDemo: false,
  },
  {
    id: "res-dl-safdarjung",
    name: "Safdarjung Hospital Emergency & One Stop Crisis Unit",
    organizationName: "Safdarjung Hospital & VMMC, New Delhi",
    serviceType: "HOSPITAL",
    description: "Designated central government hospital with 24/7 forensic medicine department, trauma triage, STI prophylaxis, and non-coercive medical attention under Section 357C CrPC/BNSS.",
    address: "Ring Road, opposite AIIMS, Safdarjung Enclave",
    state: "Delhi",
    district: "South West Delhi",
    contact: "+91-11-26165060",
    secondaryContact: "102",
    website: "https://vmmc-sjh.nic.in",
    operatingHours: "24/7",
    is24x7: true,
    eligibility: "All emergency and trauma patients",
    availability: "AVAILABLE",
    geographicScope: "DISTRICT",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_1_OFFICIAL_GOVERNMENT",
    lastVerified: "2026-08-18T00:00:00Z",
    nextReview: "2026-11-18T00:00:00Z",
    sourceOrganization: "MoHFW Hospital Registry",
    sourceUrl: "https://vmmc-sjh.nic.in",
    services: [
      { category: "MEDICAL", name: "Immediate PEP Prophylaxis (72h Window)", isFree: true },
      { category: "MEDICAL", name: "Emergency Forensic Examination & Contraception", isFree: true },
    ],
    isDemo: false,
  },
  {
    id: "res-dl-dlsa",
    name: "Delhi State Legal Services Authority (DSLSA)",
    organizationName: "DSLSA Central Office, Patiala House Courts",
    serviceType: "LEGAL_AID",
    description: "State legal authority providing round-the-clock legal aid, victim compensation scheme applications (under Section 357A CrPC / 396 BNSS), and specialized legal aid advocates.",
    address: "Central Office, Patiala House Courts Complex",
    state: "Delhi",
    district: "New Delhi",
    contact: "1516",
    secondaryContact: "+91-11-23384781",
    website: "http://dslsa.org",
    operatingHours: "10:00 AM - 5:00 PM",
    is24x7: false,
    eligibility: "Women, children, and eligible citizens seeking legal defense or representation",
    availability: "AVAILABLE",
    geographicScope: "STATE",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_1_OFFICIAL_GOVERNMENT",
    lastVerified: "2026-08-05T00:00:00Z",
    nextReview: "2026-11-05T00:00:00Z",
    sourceOrganization: "Delhi State Legal Services Authority Gazette",
    sourceUrl: "http://dslsa.org",
    services: [
      { category: "LEGAL", name: "Free Defense and Prosecution Advocate", isFree: true },
      { category: "LEGAL", name: "Delhi Victim Compensation Scheme Assistance", isFree: true },
    ],
    isDemo: false,
  },

  // ------------------------------------------------------------
  // MAHARASHTRA / MUMBAI
  // ------------------------------------------------------------
  {
    id: "res-mh-dilaasa",
    name: "Dilaasa Crisis Centre — KEM Hospital Mumbai",
    organizationName: "Public Health Dept, Municipal Corporation of Greater Mumbai & CEHAT",
    serviceType: "CRISIS_CENTER",
    description: "Pioneering hospital-based crisis center for survivors of domestic and sexual violence, providing psychological counseling, medical examination support, and safe shelter linkage.",
    address: "King Edward Memorial (KEM) Hospital, Parel",
    state: "Maharashtra",
    district: "Mumbai",
    contact: "+91-22-24107000",
    secondaryContact: "+91-9969195747",
    website: "https://www.cehat.org",
    operatingHours: "9:00 AM - 6:00 PM (Emergency medical care 24/7 via KEM Casualty)",
    is24x7: false,
    eligibility: "Women and children facing gender-based violence",
    availability: "AVAILABLE",
    geographicScope: "DISTRICT",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_2_VETTED_NGO",
    lastVerified: "2026-08-22T00:00:00Z",
    nextReview: "2026-10-22T00:00:00Z",
    sourceOrganization: "MCGM & CEHAT Joint Program Audit",
    sourceUrl: "https://www.cehat.org",
    services: [
      { category: "EMOTIONAL", name: "Trauma Counseling and Crisis Stabilization", isFree: true },
      { category: "MEDICAL", name: "KEM Casualty Forensic Linkage", isFree: true },
    ],
    isDemo: false,
  },

  // ------------------------------------------------------------
  // KARNATAKA / BENGALURU
  // ------------------------------------------------------------
  {
    id: "res-ka-nimhans-emergency",
    name: "NIMHANS Psychiatric Emergency Services",
    organizationName: "National Institute of Mental Health & Neuro Sciences (NIMHANS)",
    serviceType: "HOSPITAL",
    description: "Specialized 24/7 psychiatric emergency casualty for severe trauma, acute stress crisis, suicidal ideation, and acute emotional distress.",
    address: "Hosur Road, Lakkasandra, Bengaluru",
    state: "Karnataka",
    district: "Bengaluru Urban",
    contact: "+91-80-26995555",
    secondaryContact: "14416",
    website: "https://nimhans.ac.in",
    operatingHours: "24/7",
    is24x7: true,
    eligibility: "All psychiatric and trauma emergencies",
    availability: "AVAILABLE",
    geographicScope: "DISTRICT",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_1_OFFICIAL_GOVERNMENT",
    lastVerified: "2026-08-14T00:00:00Z",
    nextReview: "2026-11-14T00:00:00Z",
    sourceOrganization: "Ministry of Health and Family Welfare",
    sourceUrl: "https://nimhans.ac.in",
    services: [
      { category: "EMOTIONAL", name: "24/7 Acute Trauma Stabilization", isFree: true },
      { category: "MEDICAL", name: "Psychiatric Evaluation & Medication", isFree: false },
    ],
    isDemo: false,
  },
  {
    id: "res-ka-vanitha-sahayavani",
    name: "Vanitha Sahayavani (Bengaluru City Police Women Helpline)",
    organizationName: "Bengaluru City Police & Parihar",
    serviceType: "HELPLINE",
    description: "Dedicated police-linked crisis response providing on-site conflict mediation, emergency shelter admission, and female police assistance.",
    address: "Office of the Commissioner of Police, Infantry Road, Bengaluru",
    state: "Karnataka",
    district: "Bengaluru Urban",
    contact: "1091",
    secondaryContact: "+91-80-22943225",
    website: "https://bengalurucitypolice.karnataka.gov.in",
    operatingHours: "24/7",
    is24x7: true,
    eligibility: "Women and domestic distress cases in Bengaluru",
    availability: "AVAILABLE",
    geographicScope: "DISTRICT",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_1_OFFICIAL_GOVERNMENT",
    lastVerified: "2026-08-16T00:00:00Z",
    nextReview: "2026-11-16T00:00:00Z",
    sourceOrganization: "Bengaluru City Police Official Roster",
    sourceUrl: "https://bengalurucitypolice.karnataka.gov.in",
    services: [
      { category: "EMERGENCY", name: "Immediate Police Assistance", isFree: true },
      { category: "SHELTER", name: "Short-term Emergency Accommodation Placement", isFree: true },
    ],
    isDemo: false,
  },

  // ------------------------------------------------------------
  // DEMONSTRATION RESOURCES (EXPLICITLY FLAGGED WITH isDemo: true)
  // For evaluation without risk of confusing with official emergency rosters
  // ------------------------------------------------------------
  {
    id: "demo-res-001",
    name: "DEMO: Greenfield Community Safe Sanctuary",
    organizationName: "Demo Alliance for Survivor Care (Evaluation Model)",
    serviceType: "SHELTER",
    description: "A simulated non-governmental emergency shelter providing short-term transitional housing, peer group circles, and childcare support for prototype testing.",
    address: "Demo Sector 14, Prototype District",
    state: "Delhi",
    district: "South Delhi",
    contact: "+91-000-000-DEMO",
    secondaryContact: null,
    website: "https://example.org/demo-shelter",
    operatingHours: "24/7 (Simulated)",
    is24x7: true,
    eligibility: "Demonstration purpose only",
    availability: "AVAILABLE",
    geographicScope: "DISTRICT",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_3_COMMUNITY_VERIFIED",
    lastVerified: "2026-09-01T00:00:00Z",
    nextReview: "2026-10-01T00:00:00Z",
    sourceOrganization: "SecuTrail Simulation Engine",
    sourceUrl: "https://example.org",
    services: [
      { category: "SHELTER", name: "Demo Overnight Safe Beds", isFree: true },
      { category: "EMOTIONAL", name: "Demo Peer Support Circles", isFree: true },
    ],
    isDemo: true,
  },
  {
    id: "demo-res-002",
    name: "DEMO: Metro Student Legal Defense Clinic",
    organizationName: "Demo Law University Pro Bono Society",
    serviceType: "LEGAL_AID",
    description: "A simulated university-based legal aid cell offering student counseling, document drafting assistance, and mock FIR filing reviews.",
    address: "Demo University Campus, North Block",
    state: "Karnataka",
    district: "Bengaluru Urban",
    contact: "+91-000-111-TEST",
    secondaryContact: null,
    website: "https://example.org/demo-legal",
    operatingHours: "10:00 AM - 4:00 PM (Simulated)",
    is24x7: false,
    eligibility: "Demonstration purpose only",
    availability: "AVAILABLE",
    geographicScope: "DISTRICT",
    verificationStatus: "VERIFIED",
    authorityLevel: "TIER_3_COMMUNITY_VERIFIED",
    lastVerified: "2026-09-05T00:00:00Z",
    nextReview: "2026-10-05T00:00:00Z",
    sourceOrganization: "SecuTrail Simulation Engine",
    sourceUrl: "https://example.org",
    services: [
      { category: "LEGAL", name: "Demo Rights Literacy Session", isFree: true },
    ],
    isDemo: true,
  },
];
